# Generated by Django 3.2.6 on 2021-10-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created_server', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated_server', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('liters', models.IntegerField(blank=True, null=True)),
                ('price_in_cent', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
