# Generated by Django 3.2.8 on 2021-11-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuellog',
            name='advertised_price_per_liters',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
