# Generated by Django 3.2.8 on 2021-11-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_delete_vehiclelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created_server', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated_server', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('expense_name', models.CharField(blank=True, max_length=60, null=True)),
                ('expence_in_cents', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FuelLog',
        ),
    ]
