# Generated by Django 3.2.8 on 2021-12-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_necessities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Necessities',
        ),
    ]
