# Generated by Django 3.2.8 on 2021-12-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_rename_expense_name_fixedexpenses_expense_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FixedExpenses',
            new_name='Expense',
        ),
    ]
