# Generated by Django 3.2.8 on 2021-12-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_rename_fixedexpenses_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Expense_name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='expence_in_cents',
            new_name='linked_budget_id',
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='value_in_cents',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
