# Generated by Django 3.2.8 on 2021-12-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_auto_20211201_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses_list', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
