# Generated by Django 3.2.8 on 2021-12-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_auto_20211202_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='income_in_cents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='timestamp_created_server',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
