# Generated by Django 3.2.8 on 2021-12-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_auto_20211206_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='timestamp_updated_server',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
