# Generated by Django 3.2.8 on 2021-12-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_alter_budget_timestamp_updated_server'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='income_in_cents',
            new_name='remaining_this_week_in_cents',
        ),
        migrations.AddField(
            model_name='budget',
            name='fixed_expense_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='income_list_in_cents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='remaining_by_category_in_cents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='total_remaining_in_cents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='variable_expenses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
