# Generated by Django 3.2.8 on 2021-12-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_auto_20211207_1401'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='budget',
        #     old_name='fixed_expenses_list',
        #     new_name='fixed_expense',
        # ),
        migrations.RenameField(
            model_name='budget',
            old_name='income_list_in_cents',
            new_name='income_in_cents',
        ),
    ]
