# Generated by Django 3.2.8 on 2021-12-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_auto_20211207_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category_id',
        ),
    ]
