# Generated by Django 3.2.8 on 2021-12-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_auto_20211207_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='left_over_inbudget_in_cents',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
