# Generated by Django 3.2.8 on 2021-12-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0018_budget_left_over_inbudget_in_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='total_fixed_expenses_in_cents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='total_income_in_cents',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
