# Generated by Django 3.2.8 on 2021-12-31 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0019_auto_20211220_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='fixed_expense_list',
            new_name='fixed_expense',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='income_in_cents',
            new_name='income_source',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='variable_expenses',
            new_name='variable_expense',
        ),
    ]
